name: niaga_apps_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.7.0 <3.0.0"
  # sdk: '>=3.3.1 <4.0.0'
  # sdk: '>=3.7.2 <3.7.5'
  sdk: '>=2.19.2 <=3.7.2'
  # sdk: ">=3.2.0 <4.0.0"


dependencies:
  win32: ^5.5.3
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # barcode_scan: ^3.0.1
  another_stepper: ^1.2.1
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  chewie: ^1.2.2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.0
  dio: ^5.4.3+1
  # downloads_path_provider: ^0.1.0
  dropdown_search: ^5.0.6
  # dropdown_search: ^4.0.0
  equatable: ^2.0.3
  # flutter_bloc: ^0.21.0
  # file_picker: ^5.0.1
  flutter_bloc: ^8.1.6
  # flutter_clipboard_manager: ^0.0.2
  # flutter_downloader: ^1.10.5
  flutter_launcher_icons: "^0.13.1"
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^8.1.0
  # fl_chart: ^0.41.0
  # fl_chart: ^0.68.0
  fl_chart: ^0.65.0
  gallery_saver: ^2.3.1
  get_it: ^7.6.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.0.3
  # google_maps_webservice: ^0.0.15
  # http: ^1.2.1
  http: ^0.13.6
  # hydrated_bloc: ^0.4.1
  # location: ^4.2.3
  # image_gallery_saver: ^1.6.8
  intl: ^0.18.1
  local_session_timeout: ^3.2.0
  logger: ^2.0.1
  meta: ^1.8.0
  open_file: ^3.3.2
  # mobile_scanner: ^3.5.7
  overlay_support: ^2.1.0
  # path_provider: ^2.1.3
  path_provider: ^2.1.1
  # pdf: ^3.10.8
  pdf: ^3.10.1
  permission_handler: ^11.0.0
  printing: ^5.9.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.1
  # share_plus: ^9.0.0
  share_plus: ^10.1.4
  showcaseview: ^2.1.1
  # url_launcher: ^6.3.0
  url_launcher: ^6.2.5
  video_player: ^2.9.5
  webview_flutter: ^4.4.1
  # xml: ^6.3.0
  xml: ^6.2.2
  package_info_plus: ^8.3.0
  wakelock_plus: ^1.3.1

  # qr_code_scanner: ^0.1.0
  # equatable: ^2.0.5
  # flutter_bloc: ^8.1.1
  # hydrated_bloc: ^ 9.0.0
  # path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0
  build_runner: ^2.1.4
  json_serializable: ^6.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/alfamart logo.png
     - assets/alfamart.png
     - assets/aplikasi profil.png
     - assets/background-login.jpeg
     - assets/bca klikpay logo.png
     - assets/bca logo.png
     - assets/bca.png
     - assets/bg-color-grad.png
     - assets/bni logo.png
     - assets/bni.png
     - assets/bri logo.png
     - assets/bri.png
     - assets/Cancel.png
     - assets/checklist profil.png
     - assets/cimb niaga logo.png
     - assets/cimb.png
     - assets/color bg.png
     - assets/container.png
     - assets/Customer Feedback.png
     - assets/courier.png
     - assets/delivery-man.png
     - assets/Detail-Invoice.png
     - assets/edit profil.png
     - assets/fcl logo.png
     - assets/frame profil.png
     - assets/gradient-background.png
     - assets/History Pengiriman.png
     - assets/Image.png
     - assets/image home 2.png
     - assets/image home 3.png
     - assets/indomaret logo.png
     - assets/indomaret.png
     - assets/info.png
     - assets/informasi profil.png
     - assets/invoice.png
     - assets/invoice icon.png
     - assets/invoice profil.png
     - assets/Jadwal-Kapal.png
     - assets/jcb logo.png
     - assets/jcb.png
     - assets/konfirmasi fcl.png
     - assets/konfirmasi order.png
     - assets/klikpay.png
     - assets/layanan pelanggan.png
     - assets/List-Harga.png
     - assets/Logo-Detail-Invoice.png
     - assets/logo-niaga.png
     - assets/Logo Niaga.png
     - assets/logout icon profil.png
     - assets/mandiri logo.png
     - assets/mandiri.png
     - assets/mastercard logo.png
     - assets/master.png
     - assets/My-Invoice.png
    #  - assets/background-login.jpeg
     - assets/niaga-home.png
     - assets/niaga profil.png
     - assets/niaga_splash_screen.mp4
     - assets/notif history pengiriman.png
     - assets/notif register.png
     - assets/orang icon.png
     - assets/order fcl icon.png
     - assets/order lcl icon.png
     - assets/Packing-List.png
     - assets/parcel.png
     - assets/password profil.png
     - assets/pembayaran profil.png
     - assets/pembayaran qris.png
     - assets/Pemesanan.png
     - assets/pencarian profil.png
     - assets/Pengaturan Akun.png
     - assets/pencarian daftar harga.png
     - assets/Profile.png
     - assets/privasi profil.png
     - assets/qris.png
     - assets/qris logo.png
     - assets/qriss.png
    #  - assets/List-Harga.png
    #  - assets/Pemesanan.png
     - assets/scan-QR.png
     - assets/Simulasi-Pengiriman.png
     - assets/Stok-Barang.png
     - assets/storage.png
     - assets/tambah alamat.png
     - assets/telegram.png
     - assets/Tracking-Barang.png
     - assets/tracking icon.png
     - assets/truck.png
     - assets/truck new.png
     - assets/truck profil.png
     - assets/visa logo.png
     - assets/visa.png
    #  - assets/Jadwal-Kapal.png
    #  - assets/scan-QR.png
    #  - assets/Detail-Invoice.png
    #  - assets/Logo-Detail-Invoice.png
    #  - assets/telegram.png
     - assets/WA.png
     - assets/warehouse profil.png
     - assets/Warning.png
    #  - assets/Image.png
    #  - assets/Profile.png
    #  - assets/qris.png
    #  - assets/Customer Feedback.png
    #  - assets/History Pengiriman.png
    #  - assets/Pengaturan Akun.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.extrabold-italic.ttf
    - family: Poppinss
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins Med
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Extra Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    #- family: Oswald
     # fonts:
      #  - asset: assets/fonts/Oswald-Medium.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
    # android: "launcher_icon"
    android: true
    ios: true
    image_path: "assets/Logo Niaga2.png"