final List<Map<String, dynamic>> allJadwalKapal = [
  {
    'id': 1,
    'resi': 'PL/DTD-COSL/20240001',
    'tipe': 'Door to Door Stuffing Luar',
    'volume': '0.4',
    'rute': 'Jakarta - Surabaya',
    'kapal': 'SPIL Oriental Gold',
    'eta': 'ETA 17 Mar 2024',
    'etd': 'ETD 18 Mar 2024',
    'value': 'progress',
  },
  {
    'id': 2,
    'resi': 'PL/DTD-COSL/20240002',
    'tipe': 'Door to Door Stuffing Luar',
    'volume': '0.4',
    'rute': 'Semarang - Surabaya',
    'kapal': 'SPIL Oriental Gold',
    'eta': 'ETA 19 Mar 2024',
    'etd': 'ETD 20 Mar 2024',
    'value': 'completed',
  },
  {
    'id': 3,
    'resi': 'PL/DTD-COSL/20240003',
    'tipe': 'Door to Door Stuffing Luar',
    'volume': '0.4',
    'rute': 'Jakarta - Surabaya',
    'kapal': 'SPIL Oriental Gold',
    'eta': 'ETA 21 Mar 2024',
    'etd': 'ETD 22 Mar 2024',
    'value': 'completed',
  },
  {
    'id': 4,
    'resi': 'PL/DTD-COSL/20240004',
    'tipe': 'Door to Door Stuffing Luar',
    'volume': '0.24',
    'rute': 'Medan - Solo',
    'kapal': 'SPIL Oriental Gold',
    'eta': 'ETA 25 Mar 2024',
    'etd': 'ETD 27 Mar 2024',
    'value': 'progress',
  },
];
